server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      name: user
      password: 123456
eureka:
  instance:
    prefer-ip-address: true
    # hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


