logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
    # hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

#spring:
  #rabbitmq:
   # host: rabbitmq
CONFIG_SERVICE_PASSWORD: 123456
NOTIFICATION_SERVICE_PASSWORD: 123456
STATISTICS_SERVICE_PASSWORD: 123456
ACCOUNT_SERVICE_PASSWORD: 123456
MONGODB_PASSWORD: 123456